"""Add categoria column to produto table

Revision ID: fddb0d48f440
Revises: 
Create Date: 2025-05-30 15:17:09.952513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddb0d48f440'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preco_compra', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('preco_venda', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('estoque_atual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estoque_minimo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unidade_medida', sa.String(length=10), nullable=True))
        batch_op.drop_column('quantidade_minima')
        batch_op.drop_column('quantidade_estoque')
        batch_op.drop_column('preco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('quantidade_estoque', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('quantidade_minima', sa.INTEGER(), nullable=True))
        batch_op.drop_column('unidade_medida')
        batch_op.drop_column('estoque_minimo')
        batch_op.drop_column('estoque_atual')
        batch_op.drop_column('preco_venda')
        batch_op.drop_column('preco_compra')
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
